-- DML-HR.sql

-- DML (Data Manipulation Language : 데이터 조작어)
-- 데이터를 조회, 삽입, 수정, 삭제하는 SQL
-- SELECT, INSERT, UPDATE, DELETE
-- COMMIT전에는 ROLLBACK 가능, COMMIT후에는 ROLLBACK 불가

-- 데이터 조회
SELECT * FROM EMPLOYEES; -- *: 모든 컬럼
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES;
SELECT FIRST_NAME||''||LAST_NAME FROM EMPLOYEES; -- || : 문자열 접합

-- AS (ALIAS) : 별칭
SELECT FIRST_NAME||''||LAST_NAME AS FULLNAME FROM EMPLOYEES;
SELECT FIRST_NAME FN, LAST_NAME LN FROM EMPLOYEES; -- AS 생략 가능

-- 행의 수 조회
SELECT COUNT(*) AS CNT FROM EMPLOYEES; -- 107개 행
SELECT COUNT(FIRST_NAME) AS CNT FROM EMPLOYEES;
SELECT COUNT(*) FROM DEPARTMENTS; -- 27
SELECT COUNT(MANAGER_ID) FROM DEPARTMENTS; -- 11, NULL인 것은 카운트에서 제외
SELECT MANAGER_ID FROM DEPARTMENTS;

-- 문자열 접합 (CONCATENATION)
SELECT 'HELLO'||''||'ORACLE!' FROM DUAL;

-- 연산
SELECT 1+2+3+4+5 AS SUM FROM DUAL;
SELECT 10*5 AS MUL FROM DUAL;

-- DISTICT : 컬럼의 값이 같은 것들이 있으면 한번만 조회
SELECT LOCATION_ID FROM DEPARTMENTS;
SELECT COUNT(LOCATION_ID) FROM DEPARTMENTS; -- 27
SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS; -- 7
SELECT COUNT(DISTINCT LOCATION_ID) FROM DEPARTMENTS;

-- WHERE : 행에 대한 조건 부여(테이블에서 한 행씩 인출(FETCH)해서 조건을 판단)
SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 120;

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 110 AND SALARY >= 15000; -- AND 조건

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID <= 110 OR SALARY >= 15000; -- OR 조건

SELECT *
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID, 100) = 0; -- MOD : 나머지 연산 함수

-- IS NULL, IS NOT NULL
-- NULL : 데이터가 없음
SELECT *
FROM DEPARTMENTS
WHERE MANAGER_ID IS NULL;

SELECT *
FROM DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL;

-- IN : 뒤에 나오는 값 중 하나와 일치 여부
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN (10, 30, 50);

SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 10 OR DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 50;

-- BETWEEN A AND B : A와 B를 포함해서 값이 사이에 있는 지 여부
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID BETWEEN 30 AND 100;

SELECT * 
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID >= 30 AND DEPARTMENT_ID <= 100;

-- LIKE : 문자열이 어떤 패턴과 일치하는 지 여부
-- _: 문자 하나, % : 문자 0개 이상
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_____'; -- FIRST_NAME이 5글자

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%'; -- FIRST_NAME이 A로 시작

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%n'; -- FIRST_NAME이 n으로 끝

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%e%'; -- FIRST_NAME이 e를 포함

-- ORDER BY : 값에 따라 오름차순(ASC), 내림차순(DESC) 정렬
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME; -- ASC : 생략가능
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME DESC; -- DESC : 생략불가

-- 2차 정렬 : DEPARTMENT_ID 내림차순으로 1차 정렬 후 FIRST_NAME 오름차순 2차 정렬
SELECT  DEPARTMENT_ID, FIRST_NAME
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID DESC, FIRST_NAME;










