-- 테이블 생성 DDL
CREATE TABLE STUDENT (
	SID NUMBER PRIMARY KEY, -- 학번, PK
	SNAME NVARCHAR2(20) NOT NULL, -- 이름
	KOR NUMBER DEFAULT 0, -- 국어점수
	ENG NUMBER DEFAULT 0, -- 영어점수
	MATH NUMBER DEFAULT 0 -- 수학점수
);

-- 시퀀스 생성 DDL
-- 자동증가번호, 기본 1부터 1씩 증가하는 시퀀스
-- 시퀀스명.NEXTVAL: 다음번 시퀀스 값, 시퀀스명.CURRVAL: 현재 시퀀스 값
CREATE SEQUENCE SEQ_STUDENT;

-- INSERT
-- 테이블에 데이터 입력
INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '홍길동', 100, 90, 80);
INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '강감찬', 90, 80, 70);
INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '이순신', 60, 90, 40);
INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '장보고', 80, 70, 50);
INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '유관순', 70, 60, 60);
COMMIT; -- 데이터베이스에 반영

-- 일부 컬럼만 입력
INSERT INTO STUDENT(SID, SNAME)
VALUES(SEQ_STUDENT.NEXTVAL, '최영');
COMMIT; -- 데이터베이스에 반영

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '권율', 10, 10, 10);
ROLLBACK;

SELECT * FROM STUDENT;

-- UPDATE
-- 테이블의 데이터를 수정

-- UPDATE문에 WHERE절 없으면 모든 행이 수정됨 (주의!!)
-- UPDATE STUDENT
-- SET SNAME='최영장군';

UPDATE STUDENT
SET KOR=50, ENG=50, MATH=50
WHERE SID=5;
COMMIT;

-- DELETE
-- 테이블 데이터 삭제

--DELETE STUDENT; -- 주의

DELETE STUDENT
WHERE SID=10;
COMMIT;

-- INSERT ~ SELECT
-- 조회 결과를 새로운 테이블에 입력 (= 테이블 복사)
CREATE TABLE STUDENT_COPY (
	SID NUMBER PRIMARY KEY, -- 학번, PK
	SNAME NVARCHAR2(20) NOT NULL, -- 이름
	KOR NUMBER DEFAULT 0, -- 국어점수
	ENG NUMBER DEFAULT 0, -- 영어점수
	MATH NUMBER DEFAULT 0 -- 수학점수
);
CREATE SEQUENCE SEQ_STUDENT_COPY;
INSERT INTO STUDENT_COPY
SELECT * FROM STUDENT;

SELECT * FROM STUDENT_COPY;
COMMIT;













