-- DML-KMK-실습2.SQL
-- INSERT, UPDATE, DELETE 실습

-- 1) SCORE라는 테이블 생성
CREATE TABLE SCORE(
	SID NUMBER PRIMARY KEY,
	KOR NUMBER DEFAULT 0,
	ENG NUMBER DEFAULT 0,
	MATH NUMBER DEFAULT 0
);

-- 2) SEQ_SCORE라는 시퀀스 생성
CREATE SEQUENCE SEQ_SCORE;

-- 3) 데이터를 5건(행) 입력
INSERT INTO SCORE
VALUES(SEQ_SCORE.NEXTVAL, 100, 90, 80);
INSERT INTO SCORE
VALUES(SEQ_SCORE.NEXTVAL, 80, 50, 70);
INSERT INTO SCORE
VALUES(SEQ_SCORE.NEXTVAL, 90, 70, 80);
INSERT INTO SCORE
VALUES(SEQ_SCORE.NEXTVAL, 60, 50, 80);
INSERT INTO SCORE
VALUES(SEQ_SCORE.NEXTVAL, 70, 80, 40);

SELECT * FROM SCORE;

COMMIT;

-- 4) 국어점수가 70점 미만인 경우 75점으로 수정
UPDATE SCORE
SET KOR = 75
WHERE KOR < 70;
COMMIT;

-- 5) 수학점수가 50점 미만인 행들은 삭제
DELETE SCORE
WHERE MATH < 50;
COMMIT;

-- 시퀀스 삭제
-- DROP SEQUENCE SEQ_SCORE









