CREATE TABLE CCTV(
	CCTVID NUMBER PRIMARY KEY,
	LOCATION NVARCHAR2(200) NOT NULL,
	LAT NUMBER NOT NULL,
	LOG NUMBER NOT NULL,
	REGIONID NUMBER REFERENCES REGION(REGIONID) ON DELETE CASCADE
);

CREATE TABLE REGION(
	REGIONID NUMBER PRIMARY KEY,
	SI NVARCHAR2(20) NOT NULL,
	GU NVARCHAR2(20) NOT NULL,
	STARTLAT NUMBER NOT NULL,
	STARTLOG NUMBER NOT NULL,
	ENDLAT NUMBER NOT NULL,
	ENDLOG NUMBER NOT NULL
);


ALTER TABLE REGION DROP COLUMN STARTLAT;
ALTER TABLE REGION DROP COLUMN STARTLOG;
ALTER TABLE REGION DROP COLUMN ENDLAT;
ALTER TABLE REGION DROP COLUMN ENDLOG;
ALTER TABLE POLICE DROP COLUMN CLOBDATA;
ALTER TABLE POLICE ADD CLOBDATA CLOB;
ALTER TABLE CRIME ADD REGIONNAME NVARCHAR2(20);
ALTER TABLE REGION ADD SI NVARCHAR2(20);
--ALTER TABLE CRIME DROP COLUMN REGIONID;

SELECT * FROM POLICE;
SELECT * FROM region;
SELECT * FROM CRIME;

CREATE TABLE POLICE(
	POLICEID NUMBER PRIMARY KEY,
	LOCATION NVARCHAR2(200) NOT NULL,
	LAT NUMBER NOT NULL,
	LOG NUMBER NOT NULL,
	REGIONID NUMBER REFERENCES REGION(REGIONID) ON DELETE CASCADE
);

CREATE TABLE CRIME(
	CRIMEID NUMBER PRIMARY KEY,
	CRIMEYEAR NUMBER NOT NULL,
	CRIMETYPE NVARCHAR2(20) NOT NULL,
	CRIMECOUNT NUMBER NOT NULL,
	REGIONID NUMBER REFERENCES REGION(REGIONID) ON DELETE CASCADE
);

CREATE TABLE REGION_COORD(
	COORDID NUMBER PRIMARY KEY,
	LAT NUMBER NOT NULL,
	LOG NUMBER NOT NULL,
	REGIONID NUMBER REFERENCES REGION(REGIONID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REGION_COORD;
CREATE SEQUENCE SEQ_CCTV;
CREATE SEQUENCE SEQ_POLICE;
CREATE SEQUENCE SEQ_CRIME;
CREATE SEQUENCE SEQ_REGION;
DROP SEQUENCE SEQ_CRIME;

SELECT * FROM POLICE;
SELECT * FROM CRIME ORDER BY CRIMEID;
SELECT * FROM REGION;

SELECT REGIONID, SI, GU FROM REGION ORDER BY REGIONID;
SELECT CRIMEID, REGIONID, REGIONNAME FROM CRIME;
