-- 그룹핑-HR-실습.sql

-- 1) 동일한 직무를 수행하는 직원들의 직무아이디와 직원 수를 조회
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

-- 2) 동일한 월급을 받는 직원들의 월급과 직원 수를 조회
SELECT SALARY, COUNT(*)
FROM EMPLOYEES
GROUP BY SALARY;

-- 3) 부서별로 부서아이디, 소속직원수, 월급합계를 조회
--     단, 부서ID가 NULL인 것은 제외
SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID;

-- 4) 부서별로 부서아이디, 최대급여, 최소급여, 최대급여와 최소급여의 차를 조회
--    단, 부서아이디가 NULL인 것은 제외
SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY), MAX(SALARY)-MIN(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID;

-- 5) 부서별로 직원의 수가 5명 이상인 부서의 부서아이디와 직원 수를 조회
SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>=5;

-- 6) 커미션퍼센트가 NULL이 아니면서 동일한 값인 직원들의 커미션퍼센트와 직원 수를 조회
SELECT COMMISSION_PCT, COUNT(*)
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY COMMISSION_PCT; 

-- 7) 6)에서 직원수가 3~5 범위에 있는 것들만 조회
SELECT COMMISSION_PCT, COUNT(*)
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY COMMISSION_PCT
HAVING COUNT(*) BETWEEN 3 AND 5; 

-- 8) NULL이 아니고 0.3을 넘는 커미션퍼센트인 직원들에 대해
--    커미션퍼센트별로 커미션퍼센트와 직원 수를 조회
SELECT COMMISSION_PCT, COUNT(*)
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
GROUP BY COMMISSION_PCT
HAVING COMMISSION_PCT > 0.3;

-- 9) MANAGER_ID가 존재하는 부서들 중에서 LOCATION_ID별로
--    LOCATION_ID와 부서의 수를 조회
SELECT LOCATION_ID, COUNT(DEPARTMENT_ID)
FROM DEPARTMENTS
WHERE MANAGER_ID IS NOT NULL
GROUP BY LOCATION_ID;

-- 10) 부서별로 고용년도가 같은 직원들의 부서아이디와 고용년도, 직원 수를
--    부서아이디가 큰 순으로 정렬하여 조회
SELECT DEPARTMENT_ID, TO_CHAR(HIRE_DATE, 'YYYY'), COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, TO_CHAR(HIRE_DATE, 'YYYY')
ORDER BY DEPARTMENT_ID DESC;

-- 11) MANAGER_ID가 존재하는 직원들에 대해 부서별, MANAGER_ID별
--     부서아이디, 매니저아이디, 직원 수를 조회
--     단, 부서아이디가 NULL인 부서는 제외
SELECT DEPARTMENT_ID, MANAGER_ID, COUNT(*)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID, MANAGER_ID

-- 12) 국가별, 위치별, 부서별, 직무별 직원의 수를 조회
SELECT COUNTRY_ID, LOCATION_ID, DEPARTMENT_ID, JOB_ID, COUNT(*)
FROM EMP_DETAILS_VIEW
GROUP BY COUNTRY_ID, LOCATION_ID, DEPARTMENT_ID, JOB_ID;

-- 13) 연도별 입사직원의 수를 조회
SELECT TO_CHAR(HIRE_DATE, 'YYYY'), COUNT(*)
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY');

-- 14) 전화번호 중 동일한 지역번호를 사용하는 직원의 수를 조회
--       단, 지역번호는 앞 3자리로 함
SELECT SUBSTR(PHONE_NUMBER, 1, 3), COUNT(*)
FROM EMPLOYEES
GROUP BY SUBSTR(PHONE_NUMBER, 1, 3);  

-- 15) 부서별 연간총급여((월급+월급*커미션퍼센트)*12)를 산출하고
--       연간총급여가 높은 순으로 부서아이디와 연간총급여를 조회
--       단, 부서가 정해지지 않은 경우는 제외
SELECT DEPARTMENT_ID, SUM((SALARY+SALARY*NVL(COMMISSION_PCT, 0))*12) TOTAL
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL 
GROUP BY DEPARTMENT_ID
ORDER BY TOTAL DESC;

-- 16) 월급이 10000이상인 직원의 수와 10000미만인 직원의 수를 조회
SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY >= 10000
UNION
SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY < 10000;

-- SUBQUERY 버전
SELECT
	(SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY >= 10000) AS "10000이상",
	(SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY < 10000) AS "10000미만"
FROM DUAL;

-- 17) 부서명에 'IT'가 포함된 부서의 수와 그렇지 않은 부서의 수를 조회
SELECT COUNT(*)
FROM DEPARTMENTS
GROUP BY INSTR(DEPARTMENT_NAME, 'IT');

SELECT COUNT(*) FROM DEPARTMENTS
WHERE INSTR(DEPARTMENT_NAME, 'IT') > 0
UNION
SELECT COUNT(*) FROM DEPARTMENTS
WHERE INSTR(DEPARTMENT_NAME, 'IT') = 0

-- 18) 2006년 이전에 입사한 직원들의 월급합계와 2006년 이후에 입사한
--       직원들의 월급합계를 조회
SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE TO_DATE(HIRE_DATE) < TO_DATE('2006-01-01')
UNION
SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE TO_DATE(HIRE_DATE) >= TO_DATE('2007-01-01');

-- 19) 국가별, 지역별, 부서별 직원 수와 월급합계를 조회
SELECT COUNT(*), SUM(SALARY)
FROM EMP_DETAILS_VIEW
GROUP BY COUNTRY_ID, REGION_NAME, DEPARTMENT_ID

-- 20) 직무명에 'Sales'가 들어가는 직원들의 부서별 월급합계를 조회
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMP_DETAILS_VIEW
WHERE INSTR(JOB_TITLE, 'Sales')>0
GROUP BY DEPARTMENT_ID;















