-- 종합실습1-KMK.sql

-- 1. 데이터 요구사항
-- 학생들의 성적 관리
-- 엔터티 : 학생, 과목, 성적
-- 학생 엔터티 속성: 학생번호, 학생명, 이메일, 휴대폰번호
-- 과목 엔터티 속성: 과목번호, 과목명
-- 성적 엔터티 속성: 학생번호, 과목번호, 점수

-- 2. 논리/물리 모델 설계 (ERWIN)
-- SCORE.ERWIN

-- 3. 구현

-- 1) TABLE 생성
CREATE TABLE STUDENT2 (
	STNO NUMBER PRIMARY KEY,
	STNAME NVARCHAR2(200) NOT NULL,
	STEMAIL NVARCHAR2(200),
	STPHONE VARCHAR2(50)
);
CREATE TABLE SUBJECT (
	SBNO NUMBER PRIMARY KEY,
	SBNAME NVARCHAR2(200) NOT NULL
);
CREATE TABLE SCORE2 (
	POINT NUMBER(3) CHECK (POINT>=0),
	STNO NUMBER,
	SBNO NUMBER,
	FOREIGN KEY(STNO) REFERENCES STUDENT2(STNO),
	FOREIGN KEY(SBNO) REFERENCES SUBJECT(SBNO)
);
COMMIT;

--DELETE STUDENT2;
--DROP TABLE SCORE2;

-- 2) 시퀀스 생성
CREATE SEQUENCE SEQ_STUDENT2;
DROP SEQUENCE SEQ_STUDENT2;
CREATE SEQUENCE SEQ_SUBJECT;

-- 3) 데이터 입력
INSERT INTO STUDENT2 
VALUES(SEQ_STUDENT2.NEXTVAL, '홍길동', 'HONG@HONG.COM', '010-0000-0000');
INSERT INTO STUDENT2 
VALUES(SEQ_STUDENT2.NEXTVAL, '강감찬', 'KANG@KANG.COM', '010-1111-1111');
INSERT INTO STUDENT2 
VALUES(SEQ_STUDENT2.NEXTVAL, '이순신', 'LEE@LEE.COM', '010-2222-2222');

INSERT INTO SUBJECT VALUES(SEQ_SUBJECT.NEXTVAL, '국어');
INSERT INTO SUBJECT VALUES(SEQ_SUBJECT.NEXTVAL, '영어');
INSERT INTO SUBJECT VALUES(SEQ_SUBJECT.NEXTVAL, '수학');

INSERT INTO SCORE2 VALUES(100, 1, 1);
INSERT INTO SCORE2 VALUES(90, 2, 2);
INSERT INTO SCORE2 VALUES(80, 3, 3);
INSERT INTO SCORE2 VALUES(90, 1, 1);
INSERT INTO SCORE2 VALUES(80, 2, 2);
INSERT INTO SCORE2 VALUES(70, 3, 3);
INSERT INTO SCORE2 VALUES(80, 1, 1);
INSERT INTO SCORE2 VALUES(70, 2, 2);
INSERT INTO SCORE2 VALUES(60, 3, 3);

SELECT * FROM STUDENT2;
SELECT * FROM SUBJECT;
SELECT * FROM SCORE2;

COMMIT;

-- 4) 뷰 생성
CREATE  OR REPLACE VIEW VW_SCORE
AS
SELECT ST.STNAME, ST.STEMAIL, ST.STPHONE, SB.SBNAME, S.POINT
FROM STUDENT2 ST, SUBJECT SB, SCORE2 S
WHERE ST.STNO = S.STNO
	AND SB.SBNO = S.SBNO;
COMMIT;

-- 5) SYSTEM 계정에서 SCORE/SCORE 사용자 생성
--CREATE USER SCORE IDENTIFIED BY SCORE;
--GRANT CONNECT, RESOURCE TO SCORE;

-- 6) SYSTEM 계정에서 SCORE 사용자에게 VW_SCORE 조회 권한 부여
-- GRANT SELECT ON KMK.VW_SCORE TO SCORE;

-- 7) SCORE 사용자가 VW_SCORE 뷰를 조회
SELECT * FROM KMK.VW_SCORE;





















