-- 패키지-HR.sql

/*
패키지 (PACKAGE)
- 비슷한 기능을 제공하는 프로시져, 함수들을 모아놓기 위한 객체
- PACKAGE 선언부, PACKAGE 구현부 2가지로 나눔
- PACKAGE 선언부(PACKAGE) : 프로시져, 함수, 변수, 상수, 커서 등등을 선언
- PACKAGE 구현부(PACKAGE BODY) : 각각의 구현 코드를 정의
- PUBLIC ITEM : PACKAGE 선언부에 선언하고 외부에서 사용 가능
- PRIVATE ITEM : PACKAGE 구현부에 선언하고 패키지 내에서 사용 가능
*/

DROP PACKAGE PKG_EMP;

-- PACKAGE 생성
CREATE OR REPLACE PACKAGE PKG_EMP
IS

	-- 상수 선언 (PUBLIC ITEM)
	V_PUBLIC CONSTANT VARCHAR2(100) := 'PUBLIC ITEM';

	-- 프로시져 선언
	PROCEDURE PROC_TEST(P_IN IN NUMBER);
	PROCEDURE PROC_TEST2(
		P_IN IN NUMBER,
		P_OUT OUT NUMBER,
		P_INOUT IN OUT NUMBER 
	);
	PROCEDURE PROC_TEST3(
		P_IN IN NUMBER,
		P_IN2 IN NUMBER,
		P_SUM OUT NUMBER
	);

	-- 함수 선언
	FUNCTION FUNC_EMP_CNT(
		P_DEPT_ID IN EMPLOYEES.DEPARTMENT_ID%TYPE
	) RETURN NUMBER;
	FUNCTION FUNC_GETDEPTID(
		P_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE
	) RETURN NUMBER;
	FUNCTION FUNC_EMP_FULLNAME(
		P_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE
	) RETURN VARCHAR2;
END;
	
-- PACKAGE BODY	생성
CREATE OR REPLACE PACKAGE BODY PKG_EMP
IS
	
	-- 변수 (PRIVATE ITEM) 생성 및 할당
	V_PRIVATE VARCHAR2(100) := 'PRIVATE ITEM';
	
	-- 프로시져 구현
	PROCEDURE PROC_TEST(P_IN IN NUMBER)
	IS	
	BEGIN
		PL('IN 파라미터 P_IN 변수의 값: '||P_IN);
	END;
	PROCEDURE PROC_TEST2(
		P_IN IN NUMBER, -- 10
		P_OUT OUT NUMBER, -- 20(의미없음)
		P_INOUT IN OUT NUMBER -- 30
	)
	IS
	BEGIN
		PL('P_IN 변수가 전달받은 값: '||P_IN); -- 10
		PL('P_INOUT 변수가 전달받은 값: '||P_INOUT); -- 30
		P_OUT := 40;
		P_INOUT := 50;
	END;
	PROCEDURE PROC_TEST3(
		P_IN IN NUMBER,
		P_IN2 IN NUMBER,
		P_SUM OUT NUMBER
	)
	IS
	BEGIN
		P_SUM := P_IN + P_IN2;
	END;
	-- 함수 구현
	FUNCTION FUNC_EMP_CNT(
		P_DEPT_ID IN EMPLOYEES.DEPARTMENT_ID%TYPE
	) RETURN NUMBER
	IS
		V_EMP_CNT NUMBER;
	BEGIN
		SELECT COUNT(*)
		INTO V_EMP_CNT
		FROM EMPLOYEES
		WHERE DEPARTMENT_ID = P_DEPT_ID;
		RETURN V_EMP_CNT;
	END;
	FUNCTION FUNC_GETDEPTID(
		P_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE
	) RETURN NUMBER
	IS
		V_DEPT_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
	BEGIN
		SELECT DEPARTMENT_ID
		INTO V_DEPT_ID
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID = P_EMP_ID;
		RETURN V_DEPT_ID;
	END;
	FUNCTION FUNC_EMP_FULLNAME(
		P_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE
	) RETURN VARCHAR2
	IS
		V_FULLNAME VARCHAR2(46);
	BEGIN
		SELECT FIRST_NAME||' '||LAST_NAME
		INTO V_FULLNAME
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID = P_EMP_ID;
		RETURN V_FULLNAME;
	END;
END;

-- 패키지 사용

-- 패키지내 변수 사용
BEGIN
	PL(PKG_EMP.V_PUBLIC); -- 패키지 외부에서 접근 가능
--	PL(PKG_EMP.V_PRIVATE); -- 패키지 외부에서 접근 불가
END;

-- 패키지내의 프로시져 호출

DECLARE
	V_SUM NUMBER;
BEGIN
	PKG_EMP.PROC_TEST3(10, 20, V_SUM);
	PL('두 수의 합: '||V_SUM);
END;

-- 패키지내의 합수 호출
SELECT PKG_EMP.FUNC_EMP_FULLNAME(100) FROM DUAL;

























